"""create_nft_tables

Revision ID: 1789d569134d
Revises: c732647707b9
Create Date: 2025-04-18 19:07:31.869814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1789d569134d'
down_revision: Union[str, None] = 'c732647707b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nft_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nft_categories_id'), 'nft_categories', ['id'], unique=False)
    op.create_table('nfts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('coins_threshold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['nft_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfts_id'), 'nfts', ['id'], unique=False)
    op.create_table('user_nfts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'nft_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_nfts')
    op.drop_index(op.f('ix_nfts_id'), table_name='nfts')
    op.drop_table('nfts')
    op.drop_index(op.f('ix_nft_categories_id'), table_name='nft_categories')
    op.drop_table('nft_categories')
    # ### end Alembic commands ###
