"""add_daily_game_state

Revision ID: 3232a394aeef
Revises: 9b9c3f9c46b6
Create Date: 2025-04-24 19:08:27.676821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3232a394aeef'
down_revision: Union[str, None] = '9b9c3f9c46b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ton_wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ton_wallet_address')
    # ### end Alembic commands ###
