"""add_is_claimed_to_user_tasks

Revision ID: 9b9c3f9c46b6
Revises: 4a5e87ea61d7
Create Date: 2025-04-24 14:21:51.082188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9c3f9c46b6'
down_revision: Union[str, None] = '4a5e87ea61d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('is_claimed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'is_claimed')
    # ### end Alembic commands ###
