"""update_tasks_models

Revision ID: f3b01f548fb0
Revises: 3dcaace6e732
Create Date: 2025-04-20 18:39:07.992788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b01f548fb0'
down_revision: Union[str, None] = '3dcaace6e732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('user_tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'completed_at')
    op.drop_column('user_tasks', 'last_updated')
    # ### end Alembic commands ###
