"""add user ref

Revision ID: fa12bd50a043
Revises: da11d0b2a61d
Create Date: 2025-04-07 15:23:46.803312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa12bd50a043'
down_revision: Union[str, None] = 'da11d0b2a61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referred_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referred_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referred_by_id')
    # ### end Alembic commands ###
